<%@ Page Language="VB" AutoEventWireup="false" CodeFile="AdmindashBord.aspx.vb" Inherits="Admin_Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link href="../css/StyleSheet.css" rel="stylesheet" type="text/css" />
    <link href="../css/bootstrap.css" rel="stylesheet" type="text/css" />
    <title></title>
</head>
<body style=" background-image: url('../images/bgadmin.jpg');  /* Replace 'your-background-image.jpg' with your actual image file path */
            background-size: cover;
         
            background-repeat: no-repeat;">
    <form id="form1" runat="server">
     <nav class="navbar navbar-expand-lg custom-nav navbar-light fixed-top sticky">
      <div class="container">
        <a class="navbar-brand pt-0 logo" href="#">
          <img src="../images/logo1.jpeg" alt="" class="img-fluid logo-light">
          <img src="assets/images/logo-dark.png" alt="" class="img-fluid logo-dark">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="mdi mdi-menu"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto" id="main_nav">
            <li class="nav-item">
                          <asp:Button  CssClass="nav-link"  ID="adLogout" runat="server" Text="Logout" />
                         

            </li>
           
          </ul>
        </div>
      </div>
    </nav>
    <div align="center" style="padding-top:120px">
        <h1>Rivaz Admin portal</h1>
        <br />
        <br />

    
       <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" 
            BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" 
            CellPadding="10" CellSpacing="3" Font-Size="Medium" ForeColor="Black" 
            GridLines="Vertical" Width="7%" DataKeyNames="email">
             <AlternatingRowStyle BackColor="White" />
            <FooterStyle BackColor="#CCCC99" />
            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#F7F7DE" />
            <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#FBFBF2" />
            <SortedAscendingHeaderStyle BackColor="#848384" />
            <SortedDescendingCellStyle BackColor="#EAEAD3" />
            <SortedDescendingHeaderStyle BackColor="#575357" />
        </asp:GridView>

    
    </div>
    </form>
</body>
</html>
